### ISSUE TITLE
Update Batch Values - Enhancement

### ISSUE THREAD

**Issue by thomoray** [blynkkk/blynk_Issues#36]
Opening as a separate ticket but would be great if you could add timestamps to this.

This might help to eleviate some of the offline users where connectivity is of concern.

This would allow storing of data offline until connectivity is regained and then data can be uploaded filling any gaps in the data.

Cheers

Ray

**Comment by doom369** [comment]
Agree. We already planned that.

**Comment by doom369** [comment]
@thomoray added docs for the batch update via HTTPS API - https://docs.blynk.io/en/https-api/batch-update-values. Hardware API  will be added later and doc will be updated accordignly.
