### ISSUE TITLE
virtualWrite and Deepsleep on ESP32

### ISSUE THREAD

**Issue by Smartnitz** [blynkkk/blynk_Issues#48]
Hey,

I´m trying to create a very power saving product using an ESP32. Its supposed to unly upload one value to the Blynk server every few hours and then going into deepsleep mode as soon as possible. Here is a very basic example code of what I´m trying to do with boot count and 30 seconds deepsleep time:

```
#define BLYNK_TEMPLATE_ID "XXX"
#define BLYNK_DEVICE_NAME "XXX"

#define BLYNK_FIRMWARE_VERSION        "0.1.0"

#define BLYNK_PRINT Serial
#define BLYNK_DEBUG

#define APP_DEBUG

// Uncomment your board, or configure a custom board in Settings.h
//#define USE_WROVER_BOARD

#include "BlynkEdgent.h"
#include <driver/adc.h>

RTC_DATA_ATTR unsigned long bootCount = 0;

void setup(){  
  Serial.begin(115200);
  delay(100); 
  BlynkEdgent.begin();
  bootCount++;
  BLYNK_LOG("Bootcount: %ld", bootCount);
}

BLYNK_CONNECTED() {
  Blynk.virtualWrite(V104, bootCount);
  BLYNK_LOG("Upload finished");
  DeepSleep();
}

void DeepSleep() {
  Blynk.disconnect(); 
  esp_sleep_enable_timer_wakeup(30000000);  //set sleep timer to 30 seconds
  BLYNK_LOG("Going to sleep for 30 seconds...");
  esp_deep_sleep_start(); 
}

void loop() {
  BlynkEdgent.run();
}
```

This does work only sometimes. I can see only like 75% of the values on my dashboard (chart and labeled value). But from what I can see in the serial monitor everything seems to work fine - the virtualWrite command was also performed for the missing values. What did I do wrong here? Is there an easy way to check if the data upload was successfull before going to deepsleep?

**Comment by Peterkn2001** [comment]
What happens if you put this code in your `BLYNK_CONNECTED()` immediately before your `esp_deep_sleep_start();` command?

  for(int loop_count =0; loop_count <6; loop_count++)
  {
    BlynkEdgent.run();
    delay(100);
  }

Pete.

**Comment by Smartnitz** [comment]
That did make the problem worse. Now there are no more values uploaded at all. Here is a print of may serial monitor output that keeps looping:

```
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v1.0.0-beta.3 on ESP32

[255] --------------------------
[258] Product:  XXX
[261] Hardware: 1.0.0
[263] Firmware: 0.1.0 (build Apr 11 2021 11:19:43)
[268] Token:    XXX
[270] Device:   ESP32 @ 240MHz
[272] MAC:      24:0A:C4:C5:E2:E4
[275] Flash:    4096K
[277] ESP sdk:  v3.3.4-432-g7a85334d8
[281] Chip rev: 1
[283] Free mem: 274624
[285] --------------------------
[288] INIT => CONNECTING_NET
[290] Bootcount: 1
[292] Connecting to WiFi: XXX
[577] Using Dynamic IP: 192.168.2.127
[577] CONNECTING_NET => CONNECTING_CLOUD
[587] Connecting to blynk.cloud:443
[1539] Certificate OK
[1539] <[1D|00|01|00] XXX
[1581] >[00|00|01|00|C8]
[1582] Ready (ping: 41ms).
[1649] <[11|00|02|00]}ver[00]1.0.0-beta.3[00]h-beat[00]45[00]buff-in[00]1024[00]dev[00]ESP32[00]fw-type[00]TMPLIxkSIzXd[00]fw[00]0.1.0[00]build[00]Apr 11 2021 11:19:43[00]tmpl[00]TMPLIxkSIzXd[00]
[1687] >[00|00|02|00|C8]
[1723] <[14|00|03|00|08]vw[00]104[00]1
[1724] Upload finished
[1736] Connecting to blynk.cloud:443
[2670] Certificate OK
[2670] <[1D|00|01|00] XXX
[2713] >[00|00|01|00|C8]
[2713] Ready (ping: 41ms).
[2780] <[11|00|02|00]}ver[00]1.0.0-beta.3[00]h-beat[00]45[00]buff-in[00]1024[00]dev[00]ESP32[00]fw-type[00]TMPLIxkSIzXd[00]fw[00]0.1.0[00]build[00]Apr 11 2021 11:19:43[00]tmpl[00]TMPLIxkSIzXd[00]
[2855] <[14|00|03|00|08]vw[00]104[00]1
[2856] Upload finished
[32858] CONNECTING_CLOUD => ERROR
[42958] Restarting after error.
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5856
entry 0x400806a8
[254] 
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v1.0.0-beta.3 on ESP32
```

**Comment by Smartnitz** [comment]
I just tried a different approach to achive the functionality I want. My plan was to upload the boot count value when the connection to the Blynk server is established and then download the server value when there is a new one (thats what BLYNK_WRITE is doing I thought). Then compare these two values and if they match, I have the confirmation that the value was uploaded successfully and can go to deepsleep. See code:

```
void setup(){  
  Serial.begin(115200);
  delay(100); 
  BlynkEdgent.begin();
  bootCount++;
  BLYNK_LOG("Bootcount: %i", bootCount);
  timer.setInterval(60000L, DeepSleep);  // Setup DeepSleep function to be called every 60 second --> go to deep sleep if connection to Blynk server takes to long
}


BLYNK_CONNECTED() {
  Blynk.virtualWrite(V104, bootCount);
  BLYNK_LOG("Upload started");
}

BLYNK_WRITE(V104){   
  int bootCountServer = param.asInt(); // Get value as integer
  if(bootCount == bootCountServer){ //if boot count on device and server are matching --> upload has finished
    BLYNK_LOG("Upload of new boot count value confirmed");
    DeepSleep();
  }
}

void DeepSleep() {
  Blynk.disconnect(); 
  esp_sleep_enable_timer_wakeup(30000000);  //set sleep timer to 30 seconds
  BLYNK_LOG("Going to sleep for 30 seconds...");
  esp_deep_sleep_start(); //start deepsleep
}


void loop() {
  BlynkEdgent.run();
  timer.run(); // Initiates BlynkTimer
}
```
However this dosent work as expected. BLYNK_WRITE seems to trigger only when I change the boot count manually in the app, but not when I change the value on the server from my device with virtualWrite. Is that supposed to work this way?

**Comment by Peterkn2001** [comment]
You need a Blynk.syncVirtual(vPin) to make the BLYNK_WRITE(vPin) callback trigger.

Pete.

**Comment by Smartnitz** [comment]
Thanks for that tip! It works now.
But it still dosent feel like a nice solution having to download an value again to make sure it was uploaded successfully. Would it be possible to just check if I received a HTTP 200 response before going to deepsleep?

Maybe it would be possible to create an easy to use BLYNK_virtualWriteDone() or similar for that purpose?

**Comment by vshymanskyy** [comment]
Currently, the values that are sent out via `virtualWrite` are not acknowledged individually, so I think your solutions is quite good.
We'll consider adding an additional blocking API, like:
```cpp
Blynk.virtualWrite(V1, value);
Blynk.virtualWrite(V2, value2);
bool status = Blynk.waitDone();   // Wait until previous operations complete
```
But status is not 100% reliable, i.e. could be a false negative. WDYT?
