### ISSUE TITLE
Filtering shared devices

### ISSUE THREAD

**Issue by marminatix** [blynkkk/blynk_Issues#51]
Hi.
I invited a new "user" to view one of my devices but he can automatically view ALL my devices.
I'm not able to limit the visibility of only one device.
Thanks.
Marco

**Comment by doom369** [comment]
There 2 permissions for device view: `view own devices`, `view org devices`.
So you can make the user owner of the device and leave for him only "view own devices" permissions.
Another option would be to move the required device into subOrganization and invite the user to it. But it's not allowed for the Beta test.

**Comment by marminatix** [comment]
Hi.
First, I see the permissions ("view own" and "view org") on the "Roles and permissions" menu but even clicking on "EDIT" all the options are inhibited
![image](https://user-images.githubusercontent.com/81511771/114409947-3ffa1900-9bab-11eb-9f77-a7fd4ac57602.png)

Second, I've deleted myself as owner but I'm not able to assign any device to the user...
![image](https://user-images.githubusercontent.com/81511771/114410394-a0895600-9bab-11eb-9b27-ee39da6437de.png)
![image](https://user-images.githubusercontent.com/81511771/114410608-cadb1380-9bab-11eb-8bcb-5daff1441d72.png)

Some suggestions?

**Comment by doom369** [comment]
@marminatix permission granted. Now you should be able to transfer the device ownership.

**Comment by marminatix** [comment]
Yes.
The device has been successfully transferred to the user but nothing has changed in terms of changing his open permission on the others devices. 
![image](https://user-images.githubusercontent.com/81511771/114419385-aa16bc00-9bb3-11eb-9779-b2404ff4867c.png)

**Comment by marminatix** [comment]
Luca is enabled to see all the organization devices and I'm still not able to change fron "org devices" to "own devices".

**Comment by marminatix** [comment]
Today, a logistic manager has seen my superchart application to a LoRa project for the productivity measurement of a shipping line. After having appreciated the tool and asking for a quotation, the next thing was: "...where are the data? How can I retrieve/download them and/or link them to my BI tool?". Some answers?

**Comment by doom369** [comment]
> After having appreciated the tool and asking for a quotation, the next thing was: "...where are the data? How can I retrieve/download them and/or link them to my BI tool?". Some answers?

Permissions granted. Please check out the device menu.

> The device has been successfully transferred to the user but nothing has changed in terms of changing his open permission on the others devices.

What role invited user has?

**Comment by marminatix** [comment]
The invited user has only to "see" the chart and simply interact with it, without changing anything.

**Comment by marminatix** [comment]
Chart data seem all right.
Nice work

**Comment by marminatix** [comment]
@doom369 
_"What role invited user has?"_

Hi.
As in the screenshot below, editing the user permissions is still inhibited and so it's impossibile to test the device sharing with some "passive" users inside the organization.
Could this feature be enabled or is it still under development?
Thanks.
M

![image](https://user-images.githubusercontent.com/81511771/115584758-5438c700-a2cb-11eb-8eae-dd5facc7dd1a.png)

**Comment by doom369** [comment]
@marminatix added permission. Please try again.

**Comment by marminatix** [comment]
Nothing ...
All options denied.

![image](https://user-images.githubusercontent.com/81511771/115590865-c0b6c480-a2d1-11eb-955e-be72d04c43d4.png)

**Comment by marminatix** [comment]
Right now!
Permission are visible.
Close and open again the permission webpage.
Thanks

**Comment by marminatix** [comment]
I've modified ONLY the USER's privileges, restricting to "view owned devices".
Same thing if I try to ONLY exclude the user from viewing the organization's devices...
The system doesn't permit...

![image](https://user-images.githubusercontent.com/81511771/115593395-bc3fdb00-a2d4-11eb-9966-fb30b284d152.png)

**Comment by doom369** [comment]
@marminatix hm, looks like a bug. We'll check.

**Comment by marminatix** [comment]
I've tried again and I noticed that the system doesn't let me save the settings even when I ONLY try to exclude the user from viewing the organization's device.....
![image](https://user-images.githubusercontent.com/81511771/116277343-aa9f7d00-a785-11eb-8166-c09f8ac020b2.png)

**Comment by doom369** [comment]
Not fixed yet. I'll update the ticket when ready.

**Comment by marminatix** [comment]
Seems working now.
I will share a device with another user...

**Comment by blynkkk** [comment]
@marminatix can we close?
