### ISSUE TITLE
Particle Photon

### ISSUE THREAD

**Issue by peterah** [blynkkk/blynk_Issues#63]
I use Particle devices for my boards and tried to program a Particle Photon but see that their is no updated library for this platform. Is this correct, or am I looking in the wrong place? When I use the Blynk library available, the code hangs on `blynk.begin(auth);`

I thought this may be available because I am sure I saw a Photon being used in the webinar yesterday.

**Comment by jpecor** [comment]
I am having a similar problem. I can't get past a compile error.

I have a Particle Photon controlled remote switch that I manage with an existing Blynk app that I'd like to update to the new Blynk.360 and library.  I still can't get even a basic test to compile for the Photon.

Are there any examples of tested code for Particle devices available?

Thanks!

**Comment by doom369** [comment]
@vshymanskyy any advice?

**Comment by jpecor** [comment]
This is all there is to my code.  I deleted my template ID, device name and auth token for sharing, but they are there in the actual code.

```
// Fill-in information from your Blynk Template here
#define BLYNK_TEMPLATE_ID ""
#define BLYNK_DEVICE_NAME ""

#define BLYNK_FIRMWARE_VERSION        "0.1.0"

#define BLYNK_PRINT Serial
//#define BLYNK_DEBUG

#define APP_DEBUG

#include "BlynkParticle.h"

char auth[] = "";

void setup()
{
  Serial.begin(9600);
  Blynk.begin(auth);
}

void loop()
{
  Blynk.run();
}
```

And here the compile errors:

```
:::: COMPILING APPLICATION

/Users/jason/Documents/Particle/newblynk/blynktest/src/blynktest.ino: In function 'void setup()':
/Users/jason/Documents/Particle/newblynk/blynktest/src/blynktest.ino:22:3: error: 'Blynk' was not declared in this scope
   22 |   Blynk.begin(auth);
      |   ^~~~~
/Users/jason/Documents/Particle/newblynk/blynktest/src/blynktest.ino: In function 'void loop()':
/Users/jason/Documents/Particle/newblynk/blynktest/src/blynktest.ino:27:3: error: 'Blynk' was not declared in this scope
   27 |   Blynk.run();
      |   ^~~~~
make[3]: *** [../build/target/user/platform-6-m/blynktest/src/blynktest.o] Error 1
make[2]: *** [user] Error 2
make[1]: *** [modules/photon/user-part] Error 2
make: *** [compile-user] Error 2
The terminal process "/bin/bash '-c', 'make -f '/Users/jason/.particle/toolchains/buildscripts/1.10.0/Makefile' compile-user -s'" terminated with exit code: 2.
```

**Comment by vshymanskyy** [comment]
You should include this file instead of BlynkParticle.h:
```cpp
#include "BlynkSimpleParticle.h"
```

**Comment by vshymanskyy** [comment]
Verified with library v1.0.0 on Photon

**Comment by jpecor** [comment]
Thanks Volodymyr. I was able to get past the compile errors.  But now, when I try connecting from the app, I just get dancing black dots on a white screen:  From: Volodymyr Shymanskyy ***@***.***>Date: Tuesday, May 25, 2021 at 1:04 PMTo: blynkkk/blynk_Issues ***@***.***>Cc: Jason Pecor ***@***.***>, Comment ***@***.***>Subject: Re: [blynkkk/blynk_Issues] Particle Photon (#63)Verified with library v1.0.0 on Photon—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
