### ISSUE TITLE
binary data in chart widget is missing "flip" option

### ISSUE THREAD

**Issue by Smartnitz** [blynkkk/blynk_Issues#65]
Hey,

I  would like to send binary data to blynk. Datastream is configured as integer with min=0 and max=1 since there is no binary option. Anyways when I receive a value of 1 (for true) from my device in that datastream, the chart in the android widget should show it as "true". But it dosent work and shows "false" instead. The same thing worked for me in the old Blynk version since there was a "flip" option for binary data, which i had set to zero. So incoming 0 showed as false in the chart and incoming 1 showed as true.

I cant find this option in the new Blynk version :(

**Comment by doom369** [comment]
@Smartnitz do you mean Andorid or iOS app?

**Comment by Smartnitz** [comment]
android

**Comment by alexkipar** [comment]
flip option is available already in several last versions.
