### ISSUE TITLE
Chrome issue (Web version)

### ISSUE THREAD

**Issue by marminatix** [blynkkk/blynk_Issues#66]
Hi.
I'm testing an application handling some simple data transfer with a "push" data acquisition and a maximum of 1 per second refresh rate.
On the Android interface it seems all right and correctly updating numbers and graphs. On the web side (chrome browser) the flow, on superchart "latest" refresh rate, seems to periodically freeze, the browser begins to use a lot of CPU and the fan starts running. 
Refreshing the webpage doesn't work properly (the browser tries to update but without success) and doesn't solve the problem.
Solving means to close the webpage (not the browser) and open again. 
I'm sure that the issue comes from the Blynk page and only when the device is "visible" like in the screenshot below.
In the second screenshot you can see an example of chrome CPU utilization (intel i7). It usually varies between 70% and 90%...
Thanks
M

<img width="1222" alt="LoRa1" src="https://user-images.githubusercontent.com/81511771/115503724-2f1a6900-a277-11eb-9bee-3e37ebf96c0a.png">
<img width="937" alt="LoRa2" src="https://user-images.githubusercontent.com/81511771/115504575-73f2cf80-a278-11eb-8c36-588a454ee165.png">

**Comment by doom369** [comment]
@marminatix I suppose you're using "Raw" source for the Graph. Rgiht?

**Comment by marminatix** [comment]
Sorry.
I've seen such an option of "raw" data but don't rememeber "where".
Could you kindly say me where to look for?
Thanks.
M

**Comment by doom369** [comment]
@marminatix it's in the chart settings:

![screenshot-dash-qa blynk cc-2021 04 21-12_22_23](https://user-images.githubusercontent.com/1536494/115530237-43249180-a29c-11eb-879f-528b24af5b36.png)

**Comment by marminatix** [comment]
All options are on "AVG of"

![image](https://user-images.githubusercontent.com/81511771/115531930-947d5280-a295-11eb-97f0-198040f4860d.png)

**Comment by doom369** [comment]
Ok. Thanks. Definitely, graph render performance issue than.

**Comment by doom369** [comment]
@marminatix fix deployed. Please let us know if bug is still there.

**Comment by marminatix** [comment]
At a first glance it seems working properly but probably it'll take some time to be sure.
In the meanwhile, I close the issue.
If I'll see the issue again I will reopen.
M

**Comment by marminatix** [comment]
I'm sorry.
It seems the "bug" still persist.
Only Blynk cloud open, Chrome is still using about 50% of the CPU resources. And the fan runs...
On MS Edge, thing are going a little better with "only" from 15 to 25% CPU usage.
M



![image](https://user-images.githubusercontent.com/81511771/115664710-7a4d7e00-a342-11eb-9fab-34d0cbd5840a.png)
![image](https://user-images.githubusercontent.com/81511771/115664891-c5679100-a342-11eb-89f5-80cf9e43c13c.png)
![image](https://user-images.githubusercontent.com/81511771/115665177-2b541880-a343-11eb-8a4b-6c436b9e700d.png)
![image](https://user-images.githubusercontent.com/81511771/115665434-9b629e80-a343-11eb-9bfc-a2fa970bd544.png)

**Comment by marminatix** [comment]
Edge same as Chrome.
And the fan runs...

![image](https://user-images.githubusercontent.com/81511771/115666295-aff36680-a344-11eb-83a1-94ea7ce54e2b.png)

**Comment by doom369** [comment]
@marminatix hello. We deployed the new build with the fix. Please check.

**Comment by marminatix** [comment]
Testing....

**Comment by marminatix** [comment]
Hi.
The situation is better but not good enough.
The CPU usage increases with time and after 30 minutes both Crome and Edge are seizing constantly about 50% of the processor with the "lastest" update rate. No problem with other update rates. Previously, the CPU was seized in a shorter period of time at higher percentages.
Sometimes the webpage (always in "latest" mode) freezes and needs to be reloaded. This doesn't happen on the beta android app that remains perfectly updated even in "live" mode.
I suggest to assign the issue to someone else too to verify my results.
.
.
![image](https://user-images.githubusercontent.com/81511771/116088493-34761a00-a6a2-11eb-8c67-97b85236b347.png)

**Comment by Peterkn2001** [comment]
I've been trying to recreate this and I can't.
My chart widget has two datastreams, each set to "AVG of" and I've tested Chrome and Edge individually and together. After a few hours, checking the memory usage at regular intervals I've not seen CPU usage higher higher than 7% and usually it's around 2% or less for both browsers.

![image](https://user-images.githubusercontent.com/35718564/116234798-f685fe00-a754-11eb-9705-b1676b6fda1d.png)

Tested with Intel  i7-3770 CPU @ 3.40GHz on Windows 10 Pro (64 bit) version 20H2 with 16GB of memory
Chrome version 90.0.4430.85 (64 bit)
Edge version 90.0.818.49 (64 bit)

Pete.

**Comment by marminatix** [comment]
Probably I've found the solution.
Other than only the CPU over-usage, in the last days, after some device firmware upgrade, the charts began to freeze.
Of course I was using "AVG of" and the rate was one per second but in that "one per second" there were 10 Vpin pushed in.
So, of course I was an outlaw! And the system was telling me I was.... ;-)
While the android beta app (with the same widgets) wasn't affected by the situation, for sure the web page with the chart widget was.
This is only an hypothesis but in the last firmware update I reduced the pushing rate of the 10 Vpins from one per second to one per 5 seconds, so now the pushing rate has decreased from 10 Vpin per second to 2 Vpin per second.
Now the chrome CPU usage with "lastest" refresh rate is absolutely in an acceptable range around 5%!
I was wrong but I needed that data rate level because the units comes out from an assembly line with a pace of some second per piece. Anyway I've solved using the memory of the nodeMCU to store the average values.
Thank you all.

**Comment by doom369** [comment]
Thanks for the update. Yes, 1 req/sec vs 10 req/sec it's a bit different load :). 10 req/sec is not that big that the chart should lag or eat a lot of CPU. Most likely some UI elements are rendered on every request. So this should be fixed anyway.

**Comment by marminatix** [comment]
Yes.
The routine runs with 1 second pace.
My fault was thinking it was right but progressively adding Vpins brought the req/sec to 10 and not 1...
As you can see I'm not a software developer but I USE these things and I'm sure that tools will help me to improve gathering reliable data from the shop floor, to set the best modeling math for simulating the process and to be effective at the eyes of the customer.
I hope the pricing plan would be balanced enough to let us grow together....
M

**Comment by doom369** [comment]
@marminatix we deployed another possible fix. Please check again.

**Comment by marminatix** [comment]
@doom369 the rate is at 10 Vpin per second again.
Next days I'll have a better situation.
M

**Comment by marminatix** [comment]
After 1 hour. 
10 Vpins per second.

![image](https://user-images.githubusercontent.com/81511771/116658879-f5d9ab80-a990-11eb-8515-8fec4640bfdf.png)

**Comment by marminatix** [comment]
Chart freezed but label working...

<img width="1255" alt="Immagine 2021-04-30 115353" src="https://user-images.githubusercontent.com/81511771/116679548-f0895a80-a9aa-11eb-956f-397f1cb6907c.png">

**Comment by doom369** [comment]
@marminatix should be fixed. If not - please create the new ticket.
