### ISSUE TITLE
Adding device results in message: Not correct device

### ISSUE THREAD

**Issue by DaleSchultz** [blynkkk/blynk_Issues#69]
ESP8266 is flashed using device ID and name copied from web portal.
It is broadcasting a wifi AP

Adding the device on the Android app, it finds the device SSID but then says:

Not correct device.

I have tried it with and without the line: ```#define USE_NODE_MCU_BOARD```
with the same result.

![Screenshot_20210427-171648](https://user-images.githubusercontent.com/46095860/116316730-5e057300-a780-11eb-8b91-c771900c742a.png)

Console log:
```
17:33:42.352 -> [622] INIT => WAIT_CONFIG
17:33:42.962 -> [1245] AP SSID: Blynk test-64624
17:33:42.962 -> [1245] AP IP:   192.168.4.1
17:33:42.962 -> [1246] AP URL:  blynk.setup
17:34:07.932 -> [26213] WAIT_CONFIG => CONFIGURING
17:34:10.409 -> [28676] Sending board info...
17:36:46.736 -> [184992] CONFIGURING => WAIT_CONFIG
17:38:13.745 -> [272001] WAIT_CONFIG => CONFIGURING
17:38:16.221 -> [274503] Sending board info...
```

**Comment by DaleSchultz** [comment]
in the web dashboard have set the **hardware** to 

- ESP8266
- NodeMCU
- Wemos D1

and get the same result for all three.

**Comment by doom369** [comment]
@DaleSchultz is that still an issue? this error usually means that you used the wrong template id or you don't have templates at all.

**Comment by DaleSchultz** [comment]
yes nothing has changed.

Today I deleted all my templates and devices and started again
I created  a template that uses nodemcu hardware
I created 1 device that uses the single template

I placed the template ID and device name into the sketch
I flashed it to the NodeMCU

I try to add the device, it says it connects and then goes to the screen that says: NOT correct device

The name it displayed matches the new name I created today.

I only have one template and only one device that can only use the one template.

#define BLYNK_TEMPLATE_ID "TMPLsuigOkhH"
#define BLYNK_DEVICE_NAME "nodemcu"

**Comment by DaleSchultz** [comment]
and... BTW it leaves the phone connected to the temporary AP. So the phone is left offline!
When the error condition is achieved, the wifi connection to the device should be dropped.

**Comment by doom369** [comment]
@DaleSchultz do you use iOS or Android? Could you please send logs?

**Comment by DaleSchultz** [comment]
This is all that is in the log
```
App Version Name: 1.0.16 (29)
 built at 16.04.2021 18:21

 OS API Level: 30
 Model: Pixel 4a
 Manufacturer: Google

Granted Permissions: android.permission.INTERNET, android.permission.ACCESS_WIFI_STATE, android.permission.CHANGE_WIFI_STATE, android.permission.ACCESS_NETWORK_STATE, android.permission.CHANGE_NETWORK_STATE, android.permission.WAKE_LOCK, android.permission.VIBRATE, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, com.google.android.c2dm.permission.RECEIVE, com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE
```

**Comment by doom369** [comment]
@DaleSchultz that's strange. @alexkipar please advise.

**Comment by DaleSchultz** [comment]
when I created the template and device I was in the web portal.

In looking to see how to send logs, I clicked the wrench icon in the Android app.
I saw it was for creating a template on the phone. So I went back out without creating a template from the phone.

I decided to see if the log could capture the attempt to connect to the device, so I tried adding a device again.
I now get the message: Can't add new device. Create template first.
That is absolutely different to what I saw before.

So I thought, OK I'll go ahead and create a template on the phone. I did that, and tried again.
Still says:  Can't add new device. Create template first.

**Comment by doom369** [comment]
> OK I'll go ahead and create a template on the phone. I did that, and tried again.

I don't see any template on the mobile project of your account

**Comment by DaleSchultz** [comment]
In the web portal it shows me two templates I created on the phone
![image](https://user-images.githubusercontent.com/46095860/116401687-84b3c000-a7f9-11eb-90dd-d62e720784c5.png)
So the templates I created on the phone have replicated to the server.

**Comment by DaleSchultz** [comment]
the two templates I created on the phone were empty.
I created a 3rd and added a button.
Now that I have a non-empty template, it has gone back to the old behavior of saying that "not correct device"

So just having visited the developer mode forced me to create a non-empty template, even though the template I am using already exists in the cloud.

**Comment by doom369** [comment]
> Now that I have a non-empty template

That template is not the one you're trying to provision. I see you set up a mobile template with templateId = TMPLbdfXkTCi, while you add device with another template.

**Comment by DaleSchultz** [comment]
> That template is not the one you're trying to provision. I see you set up a mobile template with templateId = `TMPLbdfXkTCi`, while you add device with another template (`TMPLsuigOkhH`).

correct, but the mere presence of the template added an additional hurdle to provisioning the web-created device using the web-created template.

**Comment by DaleSchultz** [comment]
> If you created the template on the web - you don't need the new one on the mobile. You just need to connect web template with mobile template but clicking on the template name in the app in the dev mode.

understood, but remember, simply tapping the developer mode and _not_ creating a template on the phone changed the behavior of attempting to provision a device using web-created template.

**Comment by doom369** [comment]
> but remember, simply tapping the developer mode and not creating a template on the phone changed the behavior of attempting to provision a device using web-created template.

Yes. this is something we have to implement.

**Comment by DaleSchultz** [comment]
I am still not bale to progress without adding a device to the app.... should I just wait or is there something else that can be tried?

Remember the creation of templates on the phone simply raised _additional issues_. The original problem of it not provisioning still exists.

**Comment by doom369** [comment]
@DaleSchultz this one should be fixed. We did a bunch of improvements here. So i think we can close it.

**Comment by OSAMU-cooG** [comment]
I have the same problem. Did the problem go away after that?
