### ISSUE TITLE
hardware list is not sorted properly, so user thinks hardware is not in list

### ISSUE THREAD

**Issue by DaleSchultz** [blynkkk/blynk_Issues#70]
on Web portal, create a new template.

We are presented with a list of supported hardware, which appears to be sorted.
But it is only partially sorted, if one looks below 'W' we find other hardware devices.

![image](https://user-images.githubusercontent.com/46095860/116400117-ab70f700-a7f7-11eb-8213-a60128763e35.png)

Obviously the danger is that the user wont find their device in order and conclude it is not supported.

**Comment by doom369** [comment]
@DaleSchultz the list content was truncated and minimized. Now should be much better.
