### ISSUE TITLE
Usability: could not see checkbox in delete screen. 

### ISSUE THREAD

**Issue by DaleSchultz** [blynkkk/blynk_Issues#71]
I wanted to delete devices and templates

I was presented with the screen in which I have to type DELETE, but even after doing that, the delete button was not enabled.

I tried this a few times.
Eventually I noticed that the text below the DELETE field was in fact a checkbox.

I am not blind but I am over 60. A check box that is a required item needs to be made clearly visible as a checkbox and have a clearly different color to the background!

![image](https://user-images.githubusercontent.com/46095860/116400805-75804280-a7f8-11eb-9ce3-c505bd8ee943.png)

**Comment by doom369** [comment]
@DaleSchultz should be fixed. Please reopen if not.
