### ISSUE TITLE
Phone app: cannot edit empty template without creating another new one first

### ISSUE THREAD

**Issue by DaleSchultz** [blynkkk/blynk_Issues#72]
On phone app click Developer mode
Enter a template name to create a new (first) template
Do not choose any action types.
It creates an empty template. Fine.
Go back to main screen.
Tap Developer Mode to edit the existing (empty) template.

There being no non-empty templates, it insists you create a new template first. On entering a new name, one sees both.

Either non-empty templates should not be saved, or empty templates should be recognized when checking if any exist.

**Comment by doom369** [comment]
@alexkipar @eepetrash when a new template is created we always have to select some default type. Why do we allow to create the template without any type? It doesn't make any sense.

**Comment by eepetrash** [comment]
@doom369 it doesn't happen on iOS

**Comment by alexkipar** [comment]
should be fixed
