### ISSUE TITLE
'BlynkCRC32' was not declared in this scope

### ISSUE THREAD

**Issue by whogarden** [blynkkk/blynk_Issues#74]
Can not use blynk beta(version=1.0.0-beta.1) when original blynk (version=0.6.1) is present in libraries repository.
(Error 'BlynkCRC32' was not declared in this scope) when compiling the sketch "Edgent_ESP32.ino"

**Comment by vshymanskyy** [comment]
Sorry, Arduino does not support having 2 different versions of the same library.
If you need to manage libraries in a more flexible way, we suggest using advanced tools like PlatformIO
