### ISSUE TITLE
I can "start Shipping" with no devices selected

### ISSUE THREAD

**Issue by whogarden** [blynkkk/blynk_Issues#79]
I can "start Shipping" with no devices selected.
(Yes I am a little dizzy and don't see the warning at the left bottom)
The device is updated.
But the status of the shipment stays live.
and the report says "SUCCESS" (after "Cancel").
(maybe not allow to start shipping if there is no device selected).

**Comment by vshymanskyy** [comment]
This is intended. If you select no devices, a "Live" upgrade is created.
Which means, all of the devices (i.e. even newly added) of selected product will be upgraded

**Comment by whogarden** [comment]
In that case, the status stays live with green dot blinking.
(The device is successfully updated),
It seems to us that we can update nothing at all, yes we can accept that,
but in Blynk.Air the problem is :

Blynk.Air does not see the end of the update. 
And the status in Blynk.Air remains "live" for ever... And we don't know is the update is done or not.
