### ISSUE TITLE
Can't display image in Image button widget

### ISSUE THREAD

**Issue by whogarden** [blynkkk/blynk_Issues#80]
In phone app,
in "Image Button Widget", I chose to set an image to OFF STATE of an image button.
I can see the image but don't know how to set it?
![Image button](https://user-images.githubusercontent.com/16666934/118628840-480e2f80-b7cd-11eb-8623-2e076b8df6c3.jpg)

What must I do?

**Comment by whogarden** [comment]
When there is only one image on "ON STATE" (for example),
and no image on "OFF STATE"
On and Off are working, but we always see the image of "ON State".

**Comment by alexkipar** [comment]
@whogarden got it, we will enable such option.

**Comment by alexkipar** [comment]
@whogarden empty images should be a possible option now in the latest build

**Comment by whogarden** [comment]
The button name  "Update Image" is quite clear.
When There is an empty image, we can not see the button, there are no edges.
When the button is activated 2 times, it never return to "no image" and we can not see the on / off

**Comment by alexkipar** [comment]
@whogarden can you clarify what does it mean 'activated two times' ? On the setting UI for the empty case - understood.

**Comment by whogarden** [comment]
On the image button (set to "SWITH")
OFF SATE = no image
ON STATE = there is an "image2.jpg"
Start with button off
On the screen I can't see the off button( there is no image)
When I press the button, I can see the on button image  (button is on)
But now I press the button to return to off, the image should be "off button", but It's the same image (image2.jpg)
And then off button or on button always display the image of the on button.
Difficult to explain.

**Comment by whogarden** [comment]
And if you go back to an other device and come back to that device the off button shows the "on" image.
but if you disconnect then return to the device the off button shows no image (it's what we attemp to).
then one tap you see the "on" image
then one tap you see the "on" image
then one tap and you alwats see the "on" image.....

**Comment by alexkipar** [comment]
@whogarden,

I've thought that you want no image option for it not to be visible. As it is an image button - you can create any transparent image suitable for your needs and set it up for the off state. We won't implement some special no-image case with a different background for this widget.

**Comment by whogarden** [comment]
And when on settings, if I tap the on state image, 
I don't see that image and the url is empty.
I tap on delete and return in the previous screen but the on state image is always seen. (an error here)..
But back in the user screen the on image is not present (normal I deleted it)

**Comment by whogarden** [comment]
It's a misunderstanding excuse me.
At the beginning I tested with only one image on the on button.
And I saw what I describe now.

**Comment by alexkipar** [comment]
@whogarden on the refresh from on-image state to off-no-image state - I will fix it in the next update. as well in settings UI

**Comment by whogarden** [comment]
It will be fully sufficient, thank you.

**Comment by whogarden** [comment]
That's OK with Version 1.1.2(32)
