### ISSUE TITLE
In sketch I can't use virtual pins from V128 to V255

### ISSUE THREAD

**Issue by whogarden** [blynkkk/blynk_Issues#81]
In sketch (with arduino IDE and ESP8266-12F)
 I can't use virtual pins from V128 to V255.

It does nothing.

BLYNK_WRITE(V131) // Executes when the value of virtual pin 131 changes
{
  int pin_value = param.asInt();
  if (pin_value == 1)
  {
    // execute this code if the switch widget is now ON
    digitalWrite(13, LOW); // Set digital pin 13 HIGH
  }
  else
  {
    // execute this code if the switch widget is now OFF
    digitalWrite(13, HIGH); // Set digital pin 13 LOW
  }
}
![Virtual_Pin](https://user-images.githubusercontent.com/16666934/118681960-50339280-b800-11eb-9b07-5c31829e1efe.jpg)

**Comment by vshymanskyy** [comment]
@whogarden pins above `V127` have some limitations in usage, and this is properly documeted. Check out these notes:
- https://docs.blynk.io/en/blynk.edgent/api/virtual-pins#blynk_write-vpin
- https://docs.blynk.io/en/blynk.edgent/api/virtual-pins#blynk_read-vpin

> For virtual pins with numbers > 127, the `V128` syntax is not available.
> For virtual pins with numbers > 127, please use `BLYNK_WRITE_DEFAULT()` / `BLYNK_READ_DEFAULT()` API.
