### ISSUE TITLE
In mobile app selected value of "Device Reference" disappears when the information screen is refreshed

### ISSUE THREAD

**Issue by whogarden** [blynkkk/blynk_Issues#82]
A "Device Reference" was created in the (web) template Metadata.
Then for that "Device Reference" the value "Test SOS Devboard" was selected in mobile app in page "Information" of the device.
But when I refresh the screen, this value returns to "No referenced devices".

**Comment by alexkipar** [comment]
@whogarden on Tuesday there will be a new build available and this issue will be fixed

**Comment by alexkipar** [comment]
@whogarden should be fixed in the latest build

**Comment by whogarden** [comment]
When I refresh the screen, this value returns to "No referenced devices".
web dashboard was updated, and saved.
Is it ready to test?

**Comment by whogarden** [comment]
That's OK with Version 1.1.2(32)
