### ISSUE TITLE
There is only one column in the csv files

### ISSUE THREAD

**Issue by whogarden** [blynkkk/blynk_Issues#85]
When I open a csv file with excel all the datas are concentrated into only one column.
It's difficult to use...
![Comma-Semicolumn](https://user-images.githubusercontent.com/16666934/119267299-3920e600-bbee-11eb-8191-efce53a8c05f.jpg)

The reason is : 
With excel in french langage the separator is not comma but semicolon. ?
Maybe can you provide an option in settings to choose the separator that excel expects??
or some other thing.
If you replace comma by semicolon .....
![Semicolumn-Comma](https://user-images.githubusercontent.com/16666934/119267324-5fdf1c80-bbee-11eb-9faf-9e8de84c2e34.jpg)

**Comment by doom369** [comment]
@whogarden could you please provide the "bad" csv? Looks like a bug in CSV generation.

**Comment by whogarden** [comment]
Here 
[device_list_349_2021-05-24T09-13-31.zip](https://github.com/blynkkk/beta/files/6530475/device_list_349_2021-05-24T09-13-31.zip)

**Comment by whogarden** [comment]
Please delete it quickly because my email is inside

**Comment by whogarden** [comment]
There is my email inside.
Can you warn me when you'll be on line?
I'll put the file at that moment and then delete it quickly
Thank you.

**Comment by doom369** [comment]
@whogarden please send to dmitriy@blynk.cc

**Comment by whogarden** [comment]
There is my email inside.
Can you warn me when you'll be on line?
I'll put the file at that moment and then delete it quickly
Thank you.

**Comment by whogarden** [comment]
File have been sent.
Is it ok?

**Comment by doom369** [comment]
got it, thanks. we'll check.

**Comment by doom369** [comment]
Opened it with LebreOffice and all seems fine. I'll ask the QA team to check with windows and MS Office

**Comment by whogarden** [comment]
It's because the separator is a comma with excel in english...
But in France, with excel the separator is a semicolon in french MS excel... Why???
So you can not see the problem.
May be you can confirm by asking somebody in France or Belgium ......
It's something like when you apply a formula to a unix time stamp.
You use this formula : =(A1/86400)+DATE(1970,1,1)
but this formula doesn't work, in France, I must use =(A1/86400)+DATE(1970;1;1)

**Comment by doom369** [comment]
I see. You're right. Looks like both semicolon and comma are valid separators and depend on the locale. I didn't know that. Will fix.

**Comment by blynkkk** [comment]
CSV stands for `comma separated values`. Shouldn't it always be comma? :)

**Comment by whogarden** [comment]
No...
In csv files opened with Windows MS Excel,
The separator is a comma in MS excel in English (and may be other langages).
But in French (may be in other langages) the separator must be a semicolon.

(May be can you provide an option in web Blynk.cloud settings  to let the user choose the separator that excel expects?)
The default should be comma.
 Don't forget to explain this.
And it will be the user choice.

**Comment by whogarden** [comment]
May be can you have a look at this ...
https://harvestmedia.zendesk.com/hc/en-us/articles/360023978031-Opening-Excel-files-with-the-correct-CSV-list-separator

**Comment by doom369** [comment]
We'll check if we can use user locale in that case. If not - we'll add UI option.

**Comment by whogarden** [comment]
.csv files always have commas.

**Comment by doom369** [comment]
Yeah. WE made the csv generation user locale based. But at the moment only 3 locales are supported. So it can't be checked until we add more.

**Comment by whogarden** [comment]
.csv files always have commas.

**Comment by whogarden** [comment]
Pete said
It’s very easy to work around using the text to columns wizard in Excel.
https://support.microsoft.com/en-us/office/split-text-into-different-columns-with-the-convert-text-to-columns-wizard-30b14928-5550-41f5-97ca-7a3e9c363ed7
Thanks to him.
