### ISSUE TITLE
Automation has no devices for action

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk_Issues#9]
https://github.com/blynkkk/beta/issues/6#issuecomment-808701505

@alexkipar I checked the logs, looks like the issue on the Android side:

> Returning 1 getDevicesForAutomation for mobile app

**Comment by Peterkn2001** [comment]
@doom369 asked me to send my logs to this issue....

 App Version Name: 1.0.4 (6)
 built at 26.03.2021 01:13

 OS API Level: 23
 Model: Nexus 7
 Manufacturer: asus

Granted Permissions: android.permission.INTERNET,android.permission.ACCESS_WIFI_STATE,android.permission.CHANGE_WIFI_STATE,android.permission.ACCESS_NETWORK_STATE,android.permission.CHANGE_NETWORK_STATE,android.permission.ACCESS_COARSE_LOCATION,android.permission.ACCESS_FINE_LOCATION,android.permission.WAKE_LOCK,android.permission.VIBRATE,android.permission.USE_FINGERPRINT,com.google.android.c2dm.permission.RECEIVE,com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE

Pete.

**Comment by doom369** [comment]
@Peterkn2001 we did a possible fix. Could you please check if that still a case for you?

**Comment by Peterkn2001** [comment]
Okay, I've done some testing, and the functionality does now work, but there are some issues....

**Web Dashboard.**

In Template > Datastreams > [edit specific datastream] > Advanced Settings
Turning-on Expose to Automation requires an automation type to be selected. If this type (take Brightness as an example) has already been selected in a different datastream then you get a message "Product has more than one brightness datastream".

Why is there a limit of one automation type per datastream?
I'd like to have different two button widgets, both of automation type Switch, connected to two different LEDs that I can set to brightness 0 and 255 when the corresponding buttons are on. I cant do this at the moment, as I can only have one switch and one brightness automation type per template.

Also, de-selecting Expose to Automation still carries-out the duplicate automation type test on save, and there is no way to select "none" in the automation type drop-down.

Also, there is no check to see if there are any automations within the app that use this datastream's automations, before allowing it to be changed or deleted. This means that  automations can be invalidated/broken without any warning to the user.

**App.**

As above, there are no checks/warnings that automations are broken/invalidated by dashboard edits that have taken place. Some sort of integrity check is needed.

The default limit for automation actions is 1 minute, but this isn't shown anywhere ij the Add Automation screen. It's only after the datastream has been created that this limit is visible, and I was a bit confused about how to edit it, until I realised that tapping the limit frequency information gives this option.
Also, after changing this setting, the user has to click Save Automation after making this change, and there is no warning about exiting without saving. This is different to all of the other app  design screens, where simply exiting that screen saves the data (the widget settings dialogues and grid design screens for example)
Why is 1 minute the default?
Shouldn't this be settable within the Add automationdialogue?

Pete.

**Comment by doom369** [comment]
> Why is there a limit of one automation type per datastream?

Initially, this field was used for Voice Assistances. Alexa and GHome don't allow to have more than 1 brightness controller within a single device. Later, automations were introduced and we reused that field. But yeah, that's was a stupid decision and we need to divide those 2 fields.

> Also, de-selecting Expose to Automation still carries-out the duplicate automation type test on save, and there is no way to select "none" in the automation type drop-down.

That's a very good finding. A ticket created.

> Also, there is no check to see if there are any automations within the app that use this datastream's automations, before allowing it to be changed or deleted. This means that automations can be invalidated/broken without any warning to the user.

Good one. We'll think about what we can do here.

> The default limit for automation actions is 1 minute, but this isn't shown anywhere ij the Add Automation screen

Agree. @blynkkk FYI.

> Shouldn't this be settable within the Add automationdialogue?

@blynkkk please advise.
